name: get billing actions for user

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 9:00 JST

jobs:
  billing-actions-user:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Get billing actions for user
        id: billing-result
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sh get_billing_actions_for_user.sh

      - name: Dump outputs
        run: |
          echo "${{ steps.billing-result.outputs.total_minutes_used }}"
          echo "${{ steps.billing-result.outputs.total_paid_minutes_used }}"
          echo "${{ steps.billing-result.outputs.included_minutes }}"

      - name: Send Slack message
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "今月は `${{ steps.billing-result.outputs.total_minutes_used }}` 分のアクションを実行しました、無料プランでは `${{ steps.billing-result.outputs.included_minutes }}` 分まで利用できます。課金された利用時間は `${{ steps.billing-result.outputs.total_paid_minutes_used }}` 分です。"
                  }
                }
              ]
            }
