name: get billing actions for user

on: workflow_dispatch

permissions:
  contents: read

jobs:
  get-billing-actions:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Get billing actions for user
        id: billing-result
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sh get_billing_actions_for_user.sh

      - name: Dump outputs
        run: |
          echo "${{ steps.billing-result.outputs.total_minutes_used }}"
          echo "${{ steps.billing-result.outputs.total_paid_minutes_used }}"
          echo "${{ steps.billing-result.outputs.included_minutes }}"

      - name: Send Slack message
        uses: slackapi/slack-github-action@v1
        env:
          total_minutes_used: ${{ steps.billing-result.outputs.total_minutes_used }}
          total_paid_minutes_used: ${{ steps.billing-result.outputs.total_paid_minutes_used }}
          included_minutes: ${{ steps.billing-result.outputs.included_minutes }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "今月は $total_minutes_used 分のアクションを実行しました。有料プランで利用した分は $total_paid_minutes_used 分です。無料プランで利用できる分は $included_minutes 分です。"
            }
